# Copyright IBM Corp., All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.2'
services:
  initial:
    image: hyperledger/cello-operator-dashboard
    container_name: cello-initial
    links:
      - keycloak
      - mongo
    environment:
      - MONGO_URL=mongodb://cello-mongo:27017  # used by pymongo, deprecate soon
      - MONGO_HOST=mongo
      - MONGO_DB=dev
      - MONGODB_PORT=27017
      - SERVER_PUBLIC_IP=$SERVER_PUBLIC_IP
      - KEYCLOAK_REALM=$KEYCLOAK_REALM
      - KEYCLOAK_SERVER_PORT=$KEYCLOAK_SERVER_PORT
      - KEYCLOAK_ADMIN_NAME=$KEYCLOAK_ADMIN_NAME
      - KEYCLOAK_ADMIN_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD
      - OPERATOR_DASHBOARD_SSO_KEY=$OPERATOR_DASHBOARD_SSO_KEY
      - USER_DASHBOARD_SSO_KEY=$USER_DASHBOARD_SSO_KEY
      - OPERATOR_DEFAULT_ADMIN_NAME=$OPERATOR_DEFAULT_ADMIN_NAME
      - OPERATOR_DEFAULT_ADMIN_PASSWORD=$OPERATOR_DEFAULT_ADMIN_PASSWORD
    volumes:  # This should be removed in product env
      - $ROOT_PATH/src/agent/docker/_compose_files:/cello
      - $ROOT_PATH/src:/app
      - $ROOT_PATH/.makerc:/makerc
    command: bash -c "holdup -t 600 -T 600 tcp://keycloak:8080 && python /app/initial.py"

  # mongo database, may use others in future
  mongo:
    image: mongo:3.4.10
    hostname: cello-mongo
    container_name: cello-mongo
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M
        reservations:
          cpus: '0.10'
          memory: 256M
    ports:
      #- "27017:27017"  # use follow line instead in production env
      - "127.0.0.1:27017:27017"
      - "127.0.0.1:27018:27018"
    environment:
      - NO_USED=0
    volumes:
      - /opt/cello/mongo:/data/db

  mysql:
    image: mariadb:10.3.10
    container_name: cello-keycloak-mysql
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=$KEYCLOAK_DB_USERNAME
      - MYSQL_PASSWORD=$KEYCLOAK_DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$KEYCLOAK_MYSQL_ROOT_PASSWORD
    volumes:
      - /opt/cello/keycloak-mysql:/var/lib/mysql

  keycloak:
    image: jboss/keycloak:4.5.0.Final
    container_name: cello-initial-keycloak-server
    environment:
      - KEYCLOAK_USER=$KEYCLOAK_ADMIN_NAME
      - KEYCLOAK_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD
      - DB_ADDR=mysql
      - DB_USER=$KEYCLOAK_DB_USERNAME
      - DB_PASSWORD=$KEYCLOAK_DB_PASSWORD
      - KEYCLOAK_HTTPS_PORT=$KEYCLOAK_SERVER_HTTPS_PORT
    links:
      - mysql
