# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    set -eu -o pipefail
    sudo pip install --upgrade pip
    sudo pip install wheel tox
    make check
  displayName: 'make check'
