# This compose file will deploy the services, and bootup a mongo server.

# Copyright IBM Corp., All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# Local `/opt/cello/mongo` will be used for the db storage.

#  cello-nginx: proxy to access operator dashboard service, listen on 8080
#  cello-operator-dashboard: dashboard service for operators
#  cello-user-dashboard: user service of cello, listen on 8081
#  engine: engine service of cello to provide RESTful APIs, listen on 80
#  cello-mongo: mongo db

version: '3.2'
services:
  # nginx as front end for the services, disable now
  #nginx:
  #  image: hyperledger/cello-nginx
  #  hostname: cello-nginx
  #  container_name: cello-nginx
  #  restart: always
  #  deploy:
  #    resources:
  #      limits:
  #        cpus: '0.50'
  #        memory: 2048M
  #      reservations:
  #        cpus: '0.10'
  #        memory: 256M
  #  ports:
  #    - "80:80"
  #    - "8080:8080"
  #  environment:
  #    - BACKEND=cello-operator-dashboard
  #    - PORT=8080
  #    - USERNAME=admin
  #    - PASSWORD=pass

  mysql:
    image: mariadb:10.3.10
    container_name: cello-keycloak-mysql
    environment:
    - MYSQL_DATABASE=keycloak
    - MYSQL_USER=$KEYCLOAK_DB_USERNAME
    - MYSQL_PASSWORD=$KEYCLOAK_DB_PASSWORD
    - MYSQL_ROOT_PASSWORD=$KEYCLOAK_MYSQL_ROOT_PASSWORD
    volumes:
    - /opt/cello/keycloak-mysql:/var/lib/mysql

  keycloak:
    image: jboss/keycloak:4.5.0.Final
    container_name: cello-keycloak-server
    environment:
      - KEYCLOAK_USER=$KEYCLOAK_ADMIN_NAME
      - KEYCLOAK_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD
      - DB_ADDR=mysql
      - DB_USER=$KEYCLOAK_DB_USERNAME
      - DB_PASSWORD=$KEYCLOAK_DB_PASSWORD
      - KEYCLOAK_HTTPS_PORT=$KEYCLOAK_SERVER_HTTPS_PORT
    volumes:
      - $ROOT_PATH/thirdparty/keycloak/resources/img/keycloak-bg.png:/opt/jboss/keycloak/themes/keycloak/login/resources/img/keycloak-bg.png
      - $ROOT_PATH/thirdparty/keycloak/resources/img/keycloak-logo-text.png:/opt/jboss/keycloak/themes/keycloak/login/resources/img/keycloak-logo-text.png
    links:
      - mysql
    ports:
      - $KEYCLOAK_SERVER_PORT:8080
      - $KEYCLOAK_SERVER_HTTPS_PORT:8443
