---
- name: Setup variables
  set_fact:
    fabricworkdir: "/opt/gopath/{{ env }}/fabric"
    k8s_server: "{{ hostvars[groups['allnodes'][0]].private_ip }}"
    clihost: "{{ groups['allnodes'][0] }}"

- name: Stop fabric pods
  command: >-
    /opt/fabric/bin/kubectl --server {{ k8s_server }}:8080 delete 
    -f {{ fabricworkdir }}/run/fabric-pod.yml
  tags: "fabricdown"

- name: Stop fabriccli pod
  command: >-
    /opt/fabric/bin/kubectl --server {{ k8s_server }}:8080 delete
    -f {{ fabricworkdir }}/run/cli-k8s.yml
  when: clihost == inventory_hostname
  tags: "clidown"
    