---
- name: Setup variables
  set_fact:
    fabricpath: "{{ pjroot }}/vars/{{ env }}"

- name: Make sure that working directory exists
  file:
    path: "{{ pjroot }}/vars/{{ env }}/run"
    state: "directory"
    mode: 0775

- stat:
    path: "{{ fabricpath }}/bin/cryptogen"
  register: binexists

- name: Download fabric binaries
  unarchive:
    src: "{{ fabric.repo.bin }}"
    dest: "{{ fabricpath }}"
    exclude: ["config"]
    remote_src: yes
  when: fabric.repo.bin|length > 0 and binexists.stat.exists == false
  tags: "downloadbin"
