---
- name: Get start timestamp
  hosts: cloud
  connection: local
  tasks:
    - set_fact:
        starttime: "{{ ansible_date_time }}"

- name: Run the plays
  vars:
    pjroot: "{{ playbook_dir }}"
    pjrun: "{{ playbook_dir }}/vars/{{ env }}/run"
  import_playbook: "roles/cloud_{{ cloud_type | default('os') }}/plays.yml"

- name: Inform the installer
  hosts: cloud
  connection: local
  tasks:
    - debug:
        msg: >-
          The work load started at {{ hostvars.cloud.starttime.time }},
          ended at {{ ansible_date_time.time }}
