---
- name: Setup variables
  set_fact:
    fabricworkdir: "/opt/gopath/{{ env }}/fabric"

- name: Stop fabric pods
  command: >-
    ./kubectl --kubeconfig='kubeconfig' delete -f fabric-pod.yml
  args:
    chdir: "{{ playbook_dir }}/../../vars/"
  tags: "fabricdown"

- name: Reuse common code
  include_tasks: "{{ playbook_dir }}/../common/config_destroy.yml"
