---
- name: Setup variables
  set_fact:
    fabricworkdir: "/opt/gopath/{{ env }}/fabric"

- name: Stop fabric pods
  command: "./kubectl --kubeconfig='kubeconfig' apply -f fabric-pod.yml"
  args:
    chdir: "{{ playbook_dir }}/../../vars/"
  tags: "fabricdown"

- name: Test if there are any chaincode container images
  shell: docker images | grep "dev-*" | cat | awk '{print $1}'
  register: images
  no_log: true

- name: Remove these chaincode container images
  shell: docker images | grep "dev-*" | cat | awk '{print $1}' | xargs docker rmi -f
  when: images.stdout != ""
  no_log: true

- name: Make sure that working directory is removed
  file:
    path: "{{ fabricworkdir }}/run"
    state: absent
