---
# This variable defines fabric network attributes
fabric:
  peer_db: "goleveldb"
  tls: true
  consensus_type: "kafka"
  logging_level: "ERROR"
  k8s:
    exposeserviceport: True
    storageclass: "ibmc-file-gold"
    storagecapacity: "20Gi"
    shared_storage: false
    mem_req: "512Mi"
    mem_limit: "1024Mi"
    cpu_req: "0.1"
    cpu_limit: "0.2"

  network:
    fabric001:
      cas: ["ca1st.orgc"]
      peers: []
      orderers: ["orderer1st.orgc","orderer2nd.orgc","orderer3rd.orgc"]
      zookeepers: ["zookeeper1st","zookeeper2nd","zookeeper3rd"]
      kafkas: ["kafka1st","kafka2nd","kafka3rd"]

  baseimage_tag: "1.4.1"
  helper_tag: "0.4.15"
  ca:
    admin: "admin"
    adminpw: "adminpw"
    image_tag: "1.4.1"

  repo:
    url: "hyperledger/"
    username: ""
    password: ""
    bin: "https://nexus.hyperledger.org/content/repositories/snapshots/org/hyperledger/fabric/hyperledger-fabric-1.4.1-stable/linux-amd64.1.4.1-stable-SNAPSHOT/hyperledger-fabric-1.4.1-stable-linux-amd64.1.4.1-stable-20190418.020851-42.tar.gz"